# Generated by Django 3.0.4 on 2020-04-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200402_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='content',
            new_name='text',
        ),
    ]
