# Generated by Django 3.0.4 on 2020-04-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_auto_20200403_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='created_at',
        ),
    ]
